defaults:
  - pirat_upernet
checkpoint: ${paths.models_dir}/pretrain_pirat/UperNet_ConvNext_T_ADE.pth
model:
  _target_: models.UperNetForSemanticSegmentation
  backbone: ConvNeXt-T_CVST
  n_cls: 151
  pretrained: ${paths.models_dir}/init_robust_model/convnext_tiny_cvst_robust.pt
