defaults:
  - ddcatmodel
name: "pspnet_sat"
checkpoint: ${paths.models_dir}/pretrain_ddcat/cityscapes/pspnet/sat/train_epoch_400.pth
model:
  _target_: models.PSPNet
  classes: ${data.info.num_classes}
  pretrained: false
