defaults:
  - ddcatmodel
checkpoint: ${paths.models_dir}/pretrain_ddcat/voc2012/pspnet/ddcat/train_epoch_50.pth
model:
  _target_: models.PSPNet_DDCAT
  classes: ${data.info.num_classes}
  pretrained: false
